### ISSUE TITLE
HLAM 1.3 fails to load models with a length and file size mismatch error

### ISSUE THREAD

**Issue by oskarlh** [SamVanheer/HL_Tools#232] opened 2022-01-29 15:46 UTC
I tried to open [deathrun_brickwall](https://twhl.info/vault/view/5806)'s kartono_dezes.mdl, statines.mdl, vamzdziai.mdl, and zuvis2.mdl in HLAM 1.3. It fails with
![image](https://user-images.githubusercontent.com/11921030/151666494-7f450df0-56de-486a-addb-2b1d65bc6233.png)
but both HLMV and Counter-Strike 1.6 load and render the models.

I don't know if this is related to #176

PS. I started using HLAM recently and I really like it so far. I especially like the tabs

**Comment by SamVanheer** [comment] 2022-08-05 14:55
Yes this is a duplicate of #176. See that issue for my reply.

**Closed by SamVanheer** 2022-08-05 14:55 UTC
Labels: duplicate
